version: "3.9"
services:
  backend:
    build: ./backend
    working_dir: /code
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    command: "python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env.dev

  frontend:
    build: ./frontend
    working_dir: /code
    volumes:
      - ./frontend:/code
      - /code/node_modules
    ports:
      - "5173:5173"
    command: "yarn run dev"
    depends_on:
      - backend
