version: "3.9"
services:
  backend:
    image: setplay-backend
    expose:
      - 8000
    command: gunicorn setplay.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    image: setplay-frontend
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
