version: "3.9"
services:
  backend:
    build: ./backend
    volumes:
      - static_volume:/home/app/web/staticfiles
    expose:
      - 8000
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.prod

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
