# Generated by Django 4.1.3 on 2023-02-13 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("spotify", "0004_spotifytoken_modified_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spotifytoken",
            name="access_token",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="spotifytoken",
            name="refresh_token",
            field=models.CharField(max_length=300),
        ),
    ]
